steps:
  - id: 'Create env file'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo PORT=443 >> .env &&
        echo REACT_APP_BACKEND_API="http://www.markets-jp.com:8080" >> .env

  - id: 'Install dependencies'
    name: node
    entrypoint: yarn
    args: ['install']

  - id: 'Build static files'
    name: node
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "node_modules >>> " $(ls node_modules) &&
        yarn build &&
        echo ".env >>> " $(cat .env)
    # entrypoint: yarn
    # args: ['build']

  - id: 'Rename build file directory'
    name: 'ubuntu'
    args: ['mv', './build', 'html']

  - id: 'Transfer html directory with scp'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'compute',
        'scp',
        '--project',
        'markets-jp',
        '--zone',
        'asia-northeast1-b',
        '--port',
        '49152',
        '--recurse',
        './html',
        'markets-jp:/var/www',
      ]
