steps:
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: node
    entrypoint: yarn
    args: ['build']
  - name: 'bash'
    args: ['mv', './build', 'html']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'compute',
        'scp',
        '--port',
        '49152',
        '--recurse',
        './html',
        'markets-jp:/var/www',
      ]
